### ISSUE TITLE
关于初始值的问题

### ISSUE THREAD

**Issue by liuzhihai520** [vartruexuan/upload-more#2]
1. 有初始值的情况下,会调用success方法,但此时uploadMoreObj.getFileUrls()  对象没有实例化。通过上传成功出发才能使用此方法。建议都可以用。处理业务逻辑会更方便。
2. uploadBtnStatus = 2的情况下，maxNum 为多图的情况下，需要删除到所有图才会出现上传图片的界面。

感谢老哥写的插件，总体来说很实用。

**Comment by vartruexuan** [comment]
1.修复了 实际是 error回调参数位置传错了
2. uploadBtnStatus = 2 本身就是没有成员时展示上传按钮
